name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          yarn install
          yarn build
          ( sleep 10 && yarn start ) &
          while true; do curl -sL localhost:3000 1>/dev/null && break; done
          # DON'T LOOP THIS WAY: IT'S JUST A TOY
          # The point here is to be sure the server started
          # before the `mv` command that follows is run.
          # Otherwise the server will load the wrong env file

      - run: mv .env.development .env.production

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
